<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.22">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.02" />
    <PackageReference Include="MQTTnet" Version="5.2.0.1603" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HomeServer.Core\HomeServer.Core.csproj" />
    <ProjectReference Include="..\..\SDK\HomeServer.SDK\HomeServer.SDK.csproj" />
  </ItemGroup>

</Project>